### ISSUE TITLE
Credit page

### ISSUE THREAD

**Issue by quentinguidee** [quentinguidee/LavaOS#2]
#### What I want to see in the next version of LavaOS
A credit page in Settings

**Comment by MixedMatched** [comment]
Would a credit page just include the direct contributors of LavaOS or would it also include the contributors of Epsilon?

**Comment by quentinguidee** [comment]
I do not know. Basically, I thought it would be nice to add the LavaOS contributors, but now that you say it, it would be more logical to add those of Epsilon too. Only, I think there are many. What do you think?

**Comment by MixedMatched** [comment]
I think that, at a certain point, the table_view would hit its max and we wouldn't be able to display all of the cells. 29/30 is probably beyond the max. Even if it functionally could work, it would take a long time to reach even half way. We can test it, but, functionally, I think just direct contributors would be able to fit. 

We could create a different type of menu that's just text and not cells, if we wanted all contributors listed, and that would probably work if it was just some sort of child of general_sub_controller. I'm not really sure how to create that, though.

**Comment by quentinguidee** [comment]
For now, a table_view with LavaOS contributors will be enough ^^ And to avoid overloading the settings, I would suggest adding this in the "about" menu.

**Comment by quentinguidee** [comment]
* [1.7] Lava OS Contributors in settings
